// <auto-generated />
using System.Collections.Generic;
using GroupAddress.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupAddress.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241023135034_init2")]
    partial class init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("GroupAddress.Core.GA", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Addresse", "GroupAddress.Core.GA.Addresse#Addresse", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("GA")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MainGroup")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MiddleGroup")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemTemplateId");

                    b.HasIndex("MainGroupId");

                    b.ToTable("GAs");
                });

            modelBuilder.Entity("GroupAddress.Core.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubGroupNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MainGroupId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GroupAddress.Core.ItemTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubGroupNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplates");
                });

            modelBuilder.Entity("GroupAddress.Core.MainGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultBlockLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubAddress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubGroupNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MainGroups");
                });

            modelBuilder.Entity("GroupAddress.Core.GA", b =>
                {
                    b.HasOne("GroupAddress.Core.Item", null)
                        .WithMany("GAs")
                        .HasForeignKey("ItemId");

                    b.HasOne("GroupAddress.Core.ItemTemplate", null)
                        .WithMany("GAs")
                        .HasForeignKey("ItemTemplateId");

                    b.HasOne("GroupAddress.Core.MainGroup", null)
                        .WithMany("GAs")
                        .HasForeignKey("MainGroupId");
                });

            modelBuilder.Entity("GroupAddress.Core.Item", b =>
                {
                    b.HasOne("GroupAddress.Core.MainGroup", null)
                        .WithMany("Items")
                        .HasForeignKey("MainGroupId");
                });

            modelBuilder.Entity("GroupAddress.Core.Item", b =>
                {
                    b.Navigation("GAs");
                });

            modelBuilder.Entity("GroupAddress.Core.ItemTemplate", b =>
                {
                    b.Navigation("GAs");
                });

            modelBuilder.Entity("GroupAddress.Core.MainGroup", b =>
                {
                    b.Navigation("GAs");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
