// <auto-generated />
using GroupAddress.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupAddress.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241022133147_recode")]
    partial class recode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("GroupAddress.Core.GA", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubAddress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubGroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MainGroupId");

                    b.HasIndex("SubGroupId");

                    b.ToTable("GAs");
                });

            modelBuilder.Entity("GroupAddress.Core.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MainGroupId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GroupAddress.Core.MainGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultBlockLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubAddress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MainGroups");
                });

            modelBuilder.Entity("GroupAddress.Core.SubGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainGroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubAddress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MainGroupId");

                    b.ToTable("SubGroups");
                });

            modelBuilder.Entity("GroupAddress.Core.GA", b =>
                {
                    b.HasOne("GroupAddress.Core.Item", "Item")
                        .WithMany("GAs")
                        .HasForeignKey("ItemId");

                    b.HasOne("GroupAddress.Core.MainGroup", "MainGroup")
                        .WithMany("GAs")
                        .HasForeignKey("MainGroupId");

                    b.HasOne("GroupAddress.Core.SubGroup", "SubGroup")
                        .WithMany("GAs")
                        .HasForeignKey("SubGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("MainGroup");

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("GroupAddress.Core.Item", b =>
                {
                    b.HasOne("GroupAddress.Core.MainGroup", "MainGroup")
                        .WithMany("Items")
                        .HasForeignKey("MainGroupId");

                    b.Navigation("MainGroup");
                });

            modelBuilder.Entity("GroupAddress.Core.SubGroup", b =>
                {
                    b.HasOne("GroupAddress.Core.MainGroup", "MainGroup")
                        .WithMany("SubGroups")
                        .HasForeignKey("MainGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainGroup");
                });

            modelBuilder.Entity("GroupAddress.Core.Item", b =>
                {
                    b.Navigation("GAs");
                });

            modelBuilder.Entity("GroupAddress.Core.MainGroup", b =>
                {
                    b.Navigation("GAs");

                    b.Navigation("Items");

                    b.Navigation("SubGroups");
                });

            modelBuilder.Entity("GroupAddress.Core.SubGroup", b =>
                {
                    b.Navigation("GAs");
                });
#pragma warning restore 612, 618
        }
    }
}
