// <auto-generated />
using GroupAddress.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupAddress.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("GroupAddress.Core.GA", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubAddress")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SubGroupId");

                    b.ToTable("GAs");
                });

            modelBuilder.Entity("GroupAddress.Core.GATemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemTemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemTemplateId");

                    b.ToTable("GATemplate");
                });

            modelBuilder.Entity("GroupAddress.Core.GATemplatePart", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddonString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GATemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("subGroupTemplateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GATemplateId");

                    b.HasIndex("subGroupTemplateId");

                    b.ToTable("GATemplatePart");
                });

            modelBuilder.Entity("GroupAddress.Core.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GroupAddress.Core.ItemTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemTemplates");
                });

            modelBuilder.Entity("GroupAddress.Core.MainGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FillGASpaces")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FillGAToEnd")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NextItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubAddress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MainGroups");
                });

            modelBuilder.Entity("GroupAddress.Core.SubGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("MainGroupId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubAddress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MainGroupId");

                    b.ToTable("SubGroups");
                });

            modelBuilder.Entity("GroupAddress.Core.SubGroupTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubAddress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SubGroupTemplate");
                });

            modelBuilder.Entity("GroupAddress.Core.GA", b =>
                {
                    b.HasOne("GroupAddress.Core.Item", null)
                        .WithMany("GAs")
                        .HasForeignKey("ItemId");

                    b.HasOne("GroupAddress.Core.SubGroup", "SubGroup")
                        .WithMany("GAs")
                        .HasForeignKey("SubGroupId");

                    b.Navigation("SubGroup");
                });

            modelBuilder.Entity("GroupAddress.Core.GATemplate", b =>
                {
                    b.HasOne("GroupAddress.Core.ItemTemplate", null)
                        .WithMany("GATemplates")
                        .HasForeignKey("ItemTemplateId");
                });

            modelBuilder.Entity("GroupAddress.Core.GATemplatePart", b =>
                {
                    b.HasOne("GroupAddress.Core.GATemplate", null)
                        .WithMany("GAParts")
                        .HasForeignKey("GATemplateId");

                    b.HasOne("GroupAddress.Core.SubGroupTemplate", "subGroupTemplate")
                        .WithMany()
                        .HasForeignKey("subGroupTemplateId");

                    b.Navigation("subGroupTemplate");
                });

            modelBuilder.Entity("GroupAddress.Core.SubGroup", b =>
                {
                    b.HasOne("GroupAddress.Core.MainGroup", "MainGroup")
                        .WithMany("SubGroups")
                        .HasForeignKey("MainGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainGroup");
                });

            modelBuilder.Entity("GroupAddress.Core.GATemplate", b =>
                {
                    b.Navigation("GAParts");
                });

            modelBuilder.Entity("GroupAddress.Core.Item", b =>
                {
                    b.Navigation("GAs");
                });

            modelBuilder.Entity("GroupAddress.Core.ItemTemplate", b =>
                {
                    b.Navigation("GATemplates");
                });

            modelBuilder.Entity("GroupAddress.Core.MainGroup", b =>
                {
                    b.Navigation("SubGroups");
                });

            modelBuilder.Entity("GroupAddress.Core.SubGroup", b =>
                {
                    b.Navigation("GAs");
                });
#pragma warning restore 612, 618
        }
    }
}
